import {
  User,
  Event,
  Payment,
  Review,
  EventParticipant,
  SavedEvent,
  UserRole,
  EventType,
  EventStatus,
} from '../types/index'





// Sample Users
export const mockUsers: User[] = [
  {
    id: 'user-1',
    name: 'John Doe',
    email: 'john@example.com',
    password: 'password123',
    interests: ['MUSIC', 'HIKING'],
    image:
      'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&h=150&fit=crop&crop=face',
    bio: 'Adventure seeker and music lover. Always looking for new experiences!',
    location: 'New York, NY',
    role: 'USER',
    isBlocked: false,
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-15'),
    rating: 4.5,
    reviewCount: 12,
  },
  {
    id: 'user-2',
    name: 'Sarah Wilson',
    email: 'sarah@example.com',
    password: 'password123',
    interests: ['SPORTS', 'GAMING'],
    image:
      'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&h=150&fit=crop&crop=face',
    bio: 'Sports enthusiast and casual gamer. Love meeting new people!',
    location: 'Los Angeles, CA',
    role: 'HOST',
    isBlocked: false,
    createdAt: new Date('2024-01-10'),
    updatedAt: new Date('2024-01-10'),
    rating: 4.8,
    reviewCount: 28,
  },
  {
    id: 'user-3',
    name: 'Mike Johnson',
    email: 'mike@example.com',
    password: 'password123',
    interests: ['ART', 'MUSIC'],
    image:
      'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop&crop=face',
    bio: 'Art curator and concert enthusiast. Creating memorable experiences.',
    location: 'Chicago, IL',
    role: 'HOST',
    isBlocked: false,
    createdAt: new Date('2024-01-05'),
    updatedAt: new Date('2024-01-05'),
    rating: 4.9,
    reviewCount: 45,
  },
  {
    id: 'user-4',
    name: 'Emily Chen',
    email: 'emily@example.com',
    password: 'password123',
    interests: ['HIKING', 'SPORTS'],
    image:
      'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&h=150&fit=crop&crop=face',
    bio: "Outdoor adventurer and fitness coach. Let's explore together!",
    location: 'Denver, CO',
    role: 'HOST',
    isBlocked: false,
    createdAt: new Date('2024-01-08'),
    updatedAt: new Date('2024-01-08'),
    rating: 4.7,
    reviewCount: 32,
  },
  {
    id: 'user-5',
    name: 'Admin User',
    email: 'admin@example.com',
    password: 'admin123',
    interests: [],
    image:
      'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=150&h=150&fit=crop&crop=face',
    bio: 'Platform administrator',
    location: 'San Francisco, CA',
    role: 'ADMIN',
    isBlocked: false,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 'user-6',
    name: 'Alex Rivera',
    email: 'alex@example.com',
    password: 'password123',
    interests: ['GAMING', 'MUSIC'],
    image:
      'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&h=150&fit=crop&crop=face',
    bio: 'Tech enthusiast and board game collector.',
    location: 'Seattle, WA',
    role: 'USER',
    isBlocked: false,
    createdAt: new Date('2024-01-20'),
    updatedAt: new Date('2024-01-20'),
    rating: 4.3,
    reviewCount: 8,
  },
  {
    id: 'user-7',
    name: 'Jessica Park',
    email: 'jessica@example.com',
    password: 'password123',
    interests: ['ART', 'HIKING'],
    image:
      'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&h=150&fit=crop&crop=face',
    bio: 'Nature photographer and art lover.',
    location: 'Portland, OR',
    role: 'USER',
    isBlocked: false,
    createdAt: new Date('2024-01-22'),
    updatedAt: new Date('2024-01-22'),
    rating: 4.6,
    reviewCount: 15,
  },
  {
    id: 'user-8',
    name: 'David Kim',
    email: 'david@example.com',
    password: 'password123',
    interests: ['SPORTS', 'GAMING'],
    image:
      'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&h=150&fit=crop&crop=face',
    bio: 'Marathon runner and esports fan.',
    location: 'Boston, MA',
    role: 'HOST',
    isBlocked: false,
    createdAt: new Date('2024-01-12'),
    updatedAt: new Date('2024-01-12'),
    rating: 4.4,
    reviewCount: 19,
  },
  {
    id: 'user-9',
    name: 'Lisa Thompson',
    email: 'lisa@example.com',
    password: 'password123',
    interests: ['MUSIC', 'ART'],
    image:
      'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&h=150&fit=crop&crop=face',
    bio: 'Music teacher and gallery enthusiast.',
    location: 'Austin, TX',
    role: 'USER',
    isBlocked: true,
    createdAt: new Date('2024-01-25'),
    updatedAt: new Date('2024-01-25'),
    rating: 4.2,
    reviewCount: 6,
  },
  {
    id: 'user-10',
    name: 'Chris Martinez',
    email: 'chris@example.com',
    password: 'password123',
    interests: ['HIKING', 'SPORTS'],
    image:
      'https://images.unsplash.com/photo-1552058544-f2b08422138a?w=150&h=150&fit=crop&crop=face',
    bio: 'Outdoor guide and fitness instructor.',
    location: 'Phoenix, AZ',
    role: 'HOST',
    isBlocked: false,
    createdAt: new Date('2024-01-18'),
    updatedAt: new Date('2024-01-18'),
    rating: 4.9,
    reviewCount: 52,
  },
]

// Sample Events
export const mockEvents: Event[] = [
  {
    id: 'event-1',
    hostId: 'user-2',
    host: mockUsers.find((u) => u.id === 'user-2'),
    name: 'Summer Music Festival',
    description:
      'Join us for an amazing outdoor music festival featuring local bands and artists. Food trucks, drinks, and great vibes guaranteed!',
    eventType: 'CONCERT',
    dateTime: new Date('2025-02-15T18:00:00'),
    location: 'Los Angeles, CA',
    minParticipants: 10,
    maxParticipants: 100,
    currentParticipants: 45,
    image:
      'https://images.unsplash.com/photo-1459749411175-04bf5292ceea?w=800&h=400&fit=crop',
    joiningFee: 25,
    status: 'OPEN',
    isApproved: true,
    isFeatured: true,
    createdAt: new Date('2024-01-10'),
    updatedAt: new Date('2024-01-10'),
  },
  {
    id: 'event-2',
    hostId: 'user-4',
    host: mockUsers.find((u) => u.id === 'user-4'),
    name: 'Mountain Trail Hiking',
    description:
      'Explore beautiful mountain trails with fellow hiking enthusiasts. All skill levels welcome. Bring your own gear and snacks.',
    eventType: 'HIKE',
    dateTime: new Date('2025-02-20T07:00:00'),
    location: 'Denver, CO',
    minParticipants: 5,
    maxParticipants: 20,
    currentParticipants: 12,
    image:
      'https://images.unsplash.com/photo-1551632811-561732d1e306?w=800&h=400&fit=crop',
    joiningFee: 0,
    status: 'OPEN',
    isApproved: true,
    isFeatured: true,
    createdAt: new Date('2024-01-12'),
    updatedAt: new Date('2024-01-12'),
  },
  {
    id: 'event-3',
    hostId: 'user-3',
    host: mockUsers.find((u) => u.id === 'user-3'),
    name: 'Board Game Night',
    description:
      'Weekly board game night at the community center. We have a huge collection of games from classics to modern favorites.',
    eventType: 'BOARD_GAME_NIGHT',
    dateTime: new Date('2025-02-10T19:00:00'),
    location: 'Chicago, IL',
    minParticipants: 4,
    maxParticipants: 16,
    currentParticipants: 8,
    image:
      'https://images.unsplash.com/photo-1610890716171-6b1bb98ffd09?w=800&h=400&fit=crop',
    joiningFee: 5,
    status: 'OPEN',
    isApproved: true,
    isFeatured: false,
    createdAt: new Date('2024-01-08'),
    updatedAt: new Date('2024-01-08'),
  },
  {
    id: 'event-4',
    hostId: 'user-8',
    host: mockUsers.find((u) => u.id === 'user-8'),
    name: 'Tech Startup Meetup',
    description:
      'Network with fellow entrepreneurs and tech enthusiasts. Pitch your ideas, find co-founders, and learn from industry experts.',
    eventType: 'TECH_TALK',
    dateTime: new Date('2025-02-25T18:30:00'),
    location: 'Boston, MA',
    minParticipants: 15,
    maxParticipants: 50,
    currentParticipants: 32,
    image:
      'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800&h=400&fit=crop',
    joiningFee: 10,
    status: 'OPEN',
    isApproved: true,
    isFeatured: true,
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-15'),
  },
  {
    id: 'event-5',
    hostId: 'user-10',
    host: mockUsers.find((u) => u.id === 'user-10'),
    name: 'Desert Marathon Training',
    description:
      'Prepare for the upcoming desert marathon with group training sessions. Professional coaching and hydration stations provided.',
    eventType: 'MARATHON',
    dateTime: new Date('2025-03-01T06:00:00'),
    location: 'Phoenix, AZ',
    minParticipants: 10,
    maxParticipants: 30,
    currentParticipants: 30,
    image:
      'https://images.unsplash.com/photo-1552674605-db6ffd4facb5?w=800&h=400&fit=crop',
    joiningFee: 15,
    status: 'FULL',
    isApproved: true,
    isFeatured: false,
    createdAt: new Date('2024-01-20'),
    updatedAt: new Date('2024-01-20'),
  },
  {
    id: 'event-6',
    hostId: 'user-3',
    host: mockUsers.find((u) => u.id === 'user-3'),
    name: 'Modern Art Exhibition Tour',
    description:
      'Guided tour of the latest modern art exhibition. Includes exclusive access to artist meet-and-greet session.',
    eventType: 'ART_EXHIBITION',
    dateTime: new Date('2025-02-18T14:00:00'),
    location: 'Chicago, IL',
    minParticipants: 8,
    maxParticipants: 25,
    currentParticipants: 15,
    image:
      'https://images.unsplash.com/photo-1531243269054-5ebf6f34081e?w=800&h=400&fit=crop',
    joiningFee: 20,
    status: 'OPEN',
    isApproved: true,
    isFeatured: true,
    createdAt: new Date('2024-01-18'),
    updatedAt: new Date('2024-01-18'),
  },
  {
    id: 'event-7',
    hostId: 'user-2',
    host: mockUsers.find((u) => u.id === 'user-2'),
    name: 'Beach Volleyball Tournament',
    description:
      'Friendly beach volleyball tournament for all skill levels. Teams will be formed on the spot. Prizes for winners!',
    eventType: 'SPORTS',
    dateTime: new Date('2025-02-22T10:00:00'),
    location: 'Los Angeles, CA',
    minParticipants: 12,
    maxParticipants: 24,
    currentParticipants: 18,
    image:
      'https://images.unsplash.com/photo-1612872087720-bb876e2e67d1?w=800&h=400&fit=crop',
    joiningFee: 0,
    status: 'OPEN',
    isApproved: true,
    isFeatured: false,
    createdAt: new Date('2024-01-22'),
    updatedAt: new Date('2024-01-22'),
  },
  {
    id: 'event-8',
    hostId: 'user-4',
    host: mockUsers.find((u) => u.id === 'user-4'),
    name: 'Weekend Camping Trip',
    description:
      'Two-day camping adventure in the Rocky Mountains. Includes campfire cooking, stargazing, and morning yoga.',
    eventType: 'CAMPING',
    dateTime: new Date('2025-03-08T08:00:00'),
    location: 'Denver, CO',
    minParticipants: 6,
    maxParticipants: 15,
    currentParticipants: 9,
    image:
      'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=800&h=400&fit=crop',
    joiningFee: 50,
    status: 'OPEN',
    isApproved: true,
    isFeatured: true,
    createdAt: new Date('2024-01-25'),
    updatedAt: new Date('2024-01-25'),
  },
  {
    id: 'event-9',
    hostId: 'user-8',
    host: mockUsers.find((u) => u.id === 'user-8'),
    name: 'Cycling Club Meetup',
    description:
      'Weekly cycling meetup for enthusiasts. 30-mile route through scenic countryside. All bikes welcome.',
    eventType: 'CYCLING',
    dateTime: new Date('2025-02-12T07:30:00'),
    location: 'Boston, MA',
    minParticipants: 5,
    maxParticipants: 20,
    currentParticipants: 14,
    image:
      'https://images.unsplash.com/photo-1541625602330-2277a4c46182?w=800&h=400&fit=crop',
    joiningFee: 0,
    status: 'OPEN',
    isApproved: true,
    isFeatured: false,
    createdAt: new Date('2024-01-28'),
    updatedAt: new Date('2024-01-28'),
  },
  {
    id: 'event-10',
    hostId: 'user-10',
    host: mockUsers.find((u) => u.id === 'user-10'),
    name: 'Outdoor Yoga & Picnic',
    description:
      'Relaxing yoga session followed by a community picnic. Bring your own mat and a dish to share.',
    eventType: 'PICNIC',
    dateTime: new Date('2025-02-28T09:00:00'),
    location: 'Phoenix, AZ',
    minParticipants: 8,
    maxParticipants: 30,
    currentParticipants: 22,
    image:
      'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800&h=400&fit=crop',
    joiningFee: 5,
    status: 'OPEN',
    isApproved: true,
    isFeatured: false,
    createdAt: new Date('2024-01-30'),
    updatedAt: new Date('2024-01-30'),
  },
  {
    id: 'event-11',
    hostId: 'user-3',
    host: mockUsers.find((u) => u.id === 'user-3'),
    name: 'Book Club: Sci-Fi Edition',
    description:
      'Monthly book club meeting discussing classic and contemporary science fiction. This month: Dune by Frank Herbert.',
    eventType: 'BOOK_CLUB',
    dateTime: new Date('2025-02-14T19:00:00'),
    location: 'Chicago, IL',
    minParticipants: 5,
    maxParticipants: 15,
    currentParticipants: 10,
    image:
      'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=800&h=400&fit=crop',
    joiningFee: 0,
    status: 'OPEN',
    isApproved: true,
    isFeatured: false,
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-02-01'),
  },
  {
    id: 'event-12',
    hostId: 'user-2',
    host: mockUsers.find((u) => u.id === 'user-2'),
    name: 'Networking Dinner',
    description:
      'Professional networking dinner at an upscale restaurant. Great opportunity to expand your business connections.',
    eventType: 'NETWORKING_EVENT',
    dateTime: new Date('2025-03-05T19:00:00'),
    location: 'Los Angeles, CA',
    minParticipants: 10,
    maxParticipants: 40,
    currentParticipants: 28,
    image:
      'https://images.unsplash.com/photo-1517457373958-b7bdd4587205?w=800&h=400&fit=crop',
    joiningFee: 75,
    status: 'OPEN',
    isApproved: true,
    isFeatured: true,
    createdAt: new Date('2024-02-03'),
    updatedAt: new Date('2024-02-03'),
  },
  {
    id: 'event-13',
    hostId: 'user-4',
    host: mockUsers.find((u) => u.id === 'user-4'),
    name: 'Photography Workshop',
    description:
      'Learn landscape photography techniques from professional photographers. Cameras provided for beginners.',
    eventType: 'WORKSHOP',
    dateTime: new Date('2025-02-16T10:00:00'),
    location: 'Denver, CO',
    minParticipants: 6,
    maxParticipants: 12,
    currentParticipants: 12,
    image:
      'https://images.unsplash.com/photo-1542038784456-1ea8e935640e?w=800&h=400&fit=crop',
    joiningFee: 35,
    status: 'FULL',
    isApproved: true,
    isFeatured: false,
    createdAt: new Date('2024-02-05'),
    updatedAt: new Date('2024-02-05'),
  },
  {
    id: 'event-14',
    hostId: 'user-8',
    host: mockUsers.find((u) => u.id === 'user-8'),
    name: 'Movie Night: Classic Films',
    description:
      'Outdoor movie screening of classic films. Bring blankets and snacks. Popcorn provided!',
    eventType: 'MOVIE_NIGHT',
    dateTime: new Date('2025-02-21T20:00:00'),
    location: 'Boston, MA',
    minParticipants: 10,
    maxParticipants: 50,
    currentParticipants: 35,
    image:
      'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=800&h=400&fit=crop',
    joiningFee: 8,
    status: 'OPEN',
    isApproved: true,
    isFeatured: false,
    createdAt: new Date('2024-02-07'),
    updatedAt: new Date('2024-02-07'),
  },
  {
    id: 'event-15',
    hostId: 'user-10',
    host: mockUsers.find((u) => u.id === 'user-10'),
    name: 'Community Dinner Meetup',
    description:
      'Monthly community dinner where strangers become friends. Family-style dining with diverse cuisines.',
    eventType: 'DINNER',
    dateTime: new Date('2025-03-10T18:30:00'),
    location: 'Phoenix, AZ',
    minParticipants: 8,
    maxParticipants: 20,
    currentParticipants: 16,
    image:
      'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800&h=400&fit=crop',
    joiningFee: 30,
    status: 'OPEN',
    isApproved: true,
    isFeatured: false,
    createdAt: new Date('2024-02-09'),
    updatedAt: new Date('2024-02-09'),
  },
  // Past Events
  {
    id: 'event-16',
    hostId: 'user-2',
    host: mockUsers.find((u) => u.id === 'user-2'),
    name: 'New Year Concert',
    description: 'Celebrate the new year with live music and fireworks!',
    eventType: 'CONCERT',
    dateTime: new Date('2024-12-31T21:00:00'),
    location: 'Los Angeles, CA',
    minParticipants: 50,
    maxParticipants: 200,
    currentParticipants: 180,
    image:
      'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=800&h=400&fit=crop',
    joiningFee: 50,
    status: 'COMPLETED',
    isApproved: true,
    isFeatured: false,
    createdAt: new Date('2024-11-15'),
    updatedAt: new Date('2024-12-31'),
  },
  {
    id: 'event-17',
    hostId: 'user-4',
    host: mockUsers.find((u) => u.id === 'user-4'),
    name: 'Winter Hike Adventure',
    description: 'Explore snowy trails with experienced guides.',
    eventType: 'HIKE',
    dateTime: new Date('2025-01-15T08:00:00'),
    location: 'Denver, CO',
    minParticipants: 5,
    maxParticipants: 15,
    currentParticipants: 15,
    image:
      'https://images.unsplash.com/photo-1418985991508-e47386d96a71?w=800&h=400&fit=crop',
    joiningFee: 10,
    status: 'COMPLETED',
    isApproved: true,
    isFeatured: false,
    createdAt: new Date('2024-12-20'),
    updatedAt: new Date('2025-01-15'),
  },
]

// Sample Payments
export const mockPayments: Payment[] = [
  {
    id: 'payment-1',
    amount: 25,
    paymentStatus: 'PAID',
    transactionId: 'TXN-001-ABC',
    userId: 'user-1',
    user: mockUsers.find((u) => u.id === 'user-1'),
    eventId: 'event-1',
    event: mockEvents.find((e) => e.id === 'event-1'),
    createdAt: new Date('2024-01-20'),
    updatedAt: new Date('2024-01-20'),
  },
  {
    id: 'payment-2',
    amount: 10,
    paymentStatus: 'PAID',
    transactionId: 'TXN-002-DEF',
    userId: 'user-6',
    user: mockUsers.find((u) => u.id === 'user-6'),
    eventId: 'event-4',
    event: mockEvents.find((e) => e.id === 'event-4'),
    createdAt: new Date('2024-01-22'),
    updatedAt: new Date('2024-01-22'),
  },
  {
    id: 'payment-3',
    amount: 50,
    paymentStatus: 'UNPAID',
    userId: 'user-7',
    user: mockUsers.find((u) => u.id === 'user-7'),
    eventId: 'event-8',
    event: mockEvents.find((e) => e.id === 'event-8'),
    createdAt: new Date('2024-01-25'),
    updatedAt: new Date('2024-01-25'),
  },
  {
    id: 'payment-4',
    amount: 20,
    paymentStatus: 'PAID',
    transactionId: 'TXN-004-GHI',
    userId: 'user-1',
    user: mockUsers.find((u) => u.id === 'user-1'),
    eventId: 'event-6',
    event: mockEvents.find((e) => e.id === 'event-6'),
    createdAt: new Date('2024-01-28'),
    updatedAt: new Date('2024-01-28'),
  },
  {
    id: 'payment-5',
    amount: 75,
    paymentStatus: 'PAID',
    transactionId: 'TXN-005-JKL',
    userId: 'user-6',
    user: mockUsers.find((u) => u.id === 'user-6'),
    eventId: 'event-12',
    event: mockEvents.find((e) => e.id === 'event-12'),
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-02-01'),
  },
]

// Sample Reviews
export const mockReviews: Review[] = [
  {
    id: 'review-1',
    rating: 5,
    comment:
      'Amazing event! Sarah is an incredible host. Everything was well organized.',
    reviewerId: 'user-1',
    reviewer: mockUsers.find((u) => u.id === 'user-1'),
    hostId: 'user-2',
    host: mockUsers.find((u) => u.id === 'user-2'),
    eventId: 'event-1',
    event: mockEvents.find((e) => e.id === 'event-1'),
    createdAt: new Date('2024-01-25'),
    updatedAt: new Date('2024-01-25'),
  },
  {
    id: 'review-2',
    rating: 4,
    comment:
      'Great hiking experience. Would recommend to anyone who loves nature.',
    reviewerId: 'user-6',
    reviewer: mockUsers.find((u) => u.id === 'user-6'),
    hostId: 'user-4',
    host: mockUsers.find((u) => u.id === 'user-4'),
    eventId: 'event-2',
    event: mockEvents.find((e) => e.id === 'event-2'),
    createdAt: new Date('2024-01-28'),
    updatedAt: new Date('2024-01-28'),
  },
  {
    id: 'review-3',
    rating: 5,
    comment: 'Mike knows his art! The tour was informative and fun.',
    reviewerId: 'user-7',
    reviewer: mockUsers.find((u) => u.id === 'user-7'),
    hostId: 'user-3',
    host: mockUsers.find((u) => u.id === 'user-3'),
    eventId: 'event-6',
    event: mockEvents.find((e) => e.id === 'event-6'),
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-02-01'),
  },
  {
    id: 'review-4',
    rating: 5,
    comment: 'Best camping trip ever! Chris is a fantastic guide.',
    reviewerId: 'user-1',
    reviewer: mockUsers.find((u) => u.id === 'user-1'),
    hostId: 'user-10',
    host: mockUsers.find((u) => u.id === 'user-10'),
    eventId: 'event-8',
    event: mockEvents.find((e) => e.id === 'event-8'),
    createdAt: new Date('2024-02-05'),
    updatedAt: new Date('2024-02-05'),
  },
]

// Sample Event Participants
export const mockEventParticipants: EventParticipant[] = [
  {
    id: 'ep-1',
    eventId: 'event-1',
    userId: 'user-1',
    user: mockUsers.find((u) => u.id === 'user-1'),
    createdAt: new Date('2024-01-20'),
  },
  {
    id: 'ep-2',
    eventId: 'event-1',
    userId: 'user-6',
    user: mockUsers.find((u) => u.id === 'user-6'),
    createdAt: new Date('2024-01-21'),
  },
  {
    id: 'ep-3',
    eventId: 'event-1',
    userId: 'user-7',
    user: mockUsers.find((u) => u.id === 'user-7'),
    createdAt: new Date('2024-01-22'),
  },
  {
    id: 'ep-4',
    eventId: 'event-2',
    userId: 'user-1',
    user: mockUsers.find((u) => u.id === 'user-1'),
    createdAt: new Date('2024-01-23'),
  },
  {
    id: 'ep-5',
    eventId: 'event-2',
    userId: 'user-6',
    user: mockUsers.find((u) => u.id === 'user-6'),
    createdAt: new Date('2024-01-24'),
  },
  {
    id: 'ep-6',
    eventId: 'event-4',
    userId: 'user-1',
    user: mockUsers.find((u) => u.id === 'user-1'),
    createdAt: new Date('2024-01-25'),
  },
  {
    id: 'ep-7',
    eventId: 'event-6',
    userId: 'user-7',
    user: mockUsers.find((u) => u.id === 'user-7'),
    createdAt: new Date('2024-01-26'),
  },
  {
    id: 'ep-8',
    eventId: 'event-8',
    userId: 'user-1',
    user: mockUsers.find((u) => u.id === 'user-1'),
    createdAt: new Date('2024-01-27'),
  },
  {
    id: 'ep-9',
    eventId: 'event-12',
    userId: 'user-6',
    user: mockUsers.find((u) => u.id === 'user-6'),
    createdAt: new Date('2024-02-01'),
  },
]

// Sample Saved Events
export const mockSavedEvents: SavedEvent[] = [
  {
    id: 'se-1',
    eventId: 'event-1',
    userId: 'user-1',
    event: mockEvents.find((e) => e.id === 'event-1'),
    createdAt: new Date('2024-01-18'),
  },
  {
    id: 'se-2',
    eventId: 'event-2',
    userId: 'user-1',
    event: mockEvents.find((e) => e.id === 'event-2'),
    createdAt: new Date('2024-01-19'),
  },
  {
    id: 'se-3',
    eventId: 'event-8',
    userId: 'user-1',
    event: mockEvents.find((e) => e.id === 'event-8'),
    createdAt: new Date('2024-01-20'),
  },
  {
    id: 'se-4',
    eventId: 'event-4',
    userId: 'user-6',
    event: mockEvents.find((e) => e.id === 'event-4'),
    createdAt: new Date('2024-01-21'),
  },
  {
    id: 'se-5',
    eventId: 'event-12',
    userId: 'user-6',
    event: mockEvents.find((e) => e.id === 'event-12'),
    createdAt: new Date('2024-01-22'),
  },
]

// Unique Locations
export const uniqueLocations = [...new Set(mockEvents.map((e) => e.location))]

// Helper Functions
export function getEventsByHost(hostId: string): Event[] {
  return mockEvents.filter((e) => e.hostId === hostId)
}

export function getEventParticipants(eventId: string): EventParticipant[] {
  return mockEventParticipants.filter((ep) => ep.eventId === eventId)
}

export function getSavedEventsByUser(userId: string): SavedEvent[] {
  return mockSavedEvents.filter((se) => se.userId === userId)
}

export function getPaymentsByHost(hostId: string): Payment[] {
  const hostEvents = mockEvents
    .filter((e) => e.hostId === hostId)
    .map((e) => e.id)
  return mockPayments.filter((p) => hostEvents.includes(p.eventId))
}

export function getReviewsByHost(hostId: string): Review[] {
  return mockReviews.filter((r) => r.hostId === hostId)
}

export function getUserById(userId: string): User | undefined {
  return mockUsers.find((u) => u.id === userId)
}

export function getEventById(eventId: string): Event | undefined {
  return mockEvents.find((e) => e.id === eventId)
}
